"""using url instead of playlist_url in video model

Revision ID: bcdb6ec5e703
Revises: dc751a215360
Create Date: 2025-05-21 16:10:13.874470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcdb6ec5e703'
down_revision: Union[str, None] = 'dc751a215360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.String(), nullable=False))
    op.drop_column('videos', 'playlist_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('playlist_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###
